export const lastNames = [
  'Alami', 'Benali', 'Bennani', 'El Amrani', 'El Fassi',
  'Idrissi', 'Tazi', 'Alaoui', 'Benjelloun', 'Chraibi',
  'Hakimi', 'Karimi', 'Tahiri', 'Belkhadir', 'Rami',
  'Saadi', 'Qadiri', 'Ziani', 'Mansouri', 'Hilali',
  'Kadiri', 'Berrada', 'Messaoudi', 'Senhaji', 'Filali',
  'Lahlou', 'Sefrioui', 'Kettani', 'Sebti', 'Lazrak',
  'Skalli', 'Tounsi', 'Yazidi', 'Naciri', 'Squalli',
  'Lamrani', 'Slaoui', 'Ouzani', 'Cherkaoui', 'Rafii',
  'Benmoussa', 'Guessous', 'Hassani', 'Jamali', 'Nadori',
  'Ouazzani', 'Regragui', 'Sebbar', 'Tanjaoui', 'Wazzani',
  'Bouazza', 'El Ammari', 'El Harrak', 'El Jabbar', 'El Maleh',
  'El Qasem', 'El Ouazzan', 'El Youssouf', 'Fadel', 'Farah',
  'Haddad', 'Hamoud', 'Hassan', 'Jouah', 'Kabbaj',
  'Kaddour', 'Kafou', 'Kamel', 'Khabbaz', 'Lamjarred',
  'Mahfoud', 'Marrakch', 'Moumen', 'El Khayatt', 'El Ouarrak',
  'El Kaddour', 'El Marrakch', 'El Mesbahi', 'El Messahel', 'El Moussaou',
  'El Qandous', 'El Yamah', 'Guenoun', 'Jabar', 'Khalaf',
  'Khammar', 'Lazaar', 'Lmrabet', 'Mouhtad', 'Nour',
  'Saada', 'Sabbah', 'Sabour', 'Salek', 'Sekkat',
  'Talal', 'Zahraw', 'Boulahfa', 'Shama'
];

export const femaleNames = [
  'Fatima', 'Amina', 'Khadija', 'Aisha', 'Zineb',
  'Salma', 'Yasmine', 'Sanaa', 'Nadia', 'Samira',
  'Laila', 'Malika', 'Karima', 'Latifa', 'Nabila',
  'Hafsa', 'Imane', 'Soukaina', 'Ghita', 'Meriem',
  'Houda', 'Rajae', 'Nezha', 'Siham', 'Wafa',
  'Hanane', 'Btissam', 'Jamila', 'Nawal', 'Hayat',
  'Loubna', 'Rachida', 'Safae', 'Zhor', 'Ilham',
  'Fadwa', 'Lamiaa', 'Khaoula', 'Dounia', 'Rim',
  'Amal', 'Noura', 'Saida', 'Chaimae', 'Ikram',
  'Soraya', 'Mouna', 'Asma', 'Fatiha', 'Naima',
  'Hajar', 'Sara', 'Manal', 'Rania', 'Samar',
  'Kenza', 'Oumaima', 'Youssra', 'Hiba', 'Nada',
  'Oualid', 'Marwa', 'Rihab', 'Chahinez', 'Inès',
  'Dina', 'Jihane', 'Yousra', 'Hasna', 'Raja',
  'Jalila', 'Aya', 'Ibtissam', 'Ferial', 'Chaymae',
  'Zahra', 'Wiam', 'Sabah', 'Fouzia', 'Hind',
  'Meryem', 'Samah', 'Hanan', 'Abla', 'Basma',
  'Farida', 'Hasnaa', 'Kamar', 'Lina', 'Maha',
  'Moufida', 'Narjiss', 'Oumnia', 'Rabab', 'Randa',
  'Siham', 'Wissal', 'Zahia', 'Keltoum', 'Zohra'
];

export const maleNames = [
  'Mohammed', 'Ahmed', 'Youssef', 'Hassan', 'Omar',
  'Khalid', 'Rachid', 'Karim', 'Mehdi', 'Amine',
  'Hamza', 'Samir', 'Abdelaziz', 'Tarik', 'Hicham',
  'Mustapha', 'Zakaria', 'Othmane', 'Adil', 'Nabil',
  'Driss', 'Jamal', 'Ismail', 'Ayoub', 'Anas',
  'Abderrahim', 'Yassine', 'Brahim', 'Said', 'Badr',
  'Bilal', 'Aziz', 'Fouad', 'Abdellah', 'Soufiane',
  'Redouane', 'Hakim', 'Mounir', 'Walid', 'Malek',
  'Anass', 'Hatim', 'Houssam', 'Ilyas', 'Elias',
  'Abdessamad', 'Yahya', 'Sofian', 'Noureddine', 'Larbi',
  'Ali', 'Mohcine', 'Salaheddine', 'Zouhair', 'Kamal',
  'Jalil', 'Marouane', 'Ziad', 'Adnane', 'Mourad',
  'Hicham', 'Chakib', 'Jaouad', 'Taha', 'Fares',
  'Faouzi', 'Majid', 'Oussama', 'Rayan', 'Marwan',
  'Nezar', 'Younes', 'Adel', 'Bouchaib', 'Charaf',
  'Hamid', 'Idriss', 'Jawad', 'Kacem', 'Lamine',
  'Mansour', 'Moad', 'Mokhtar', 'Nawfal', 'Rida',
  'Saad', 'Taoufik', 'Yassir', 'Zine', 'Ammar',
  'Chouaib', 'Essam', 'Fahd', 'Ghani', 'Ibrahim',
  'Issam', 'Jaber', 'Louay', 'Saber', 'Wassim'
];

export const sections = ["A", "B", "C", "D", "E", "F"]

export const streets = [
  'Avenue Mohammed V',
  'Rue Hassan II',
  'Boulevard Zerktouni',
  'Rue Allal Ben Abdellah',
  'Avenue des FAR',
  'Rue de la Liberté',
  'Boulevard Moulay Youssef',
  'Rue Abdelmoumen',
  'Avenue Al Massira Al Khadra',
  'Rue Ibn Tachfine',
  'Boulevard Anfa',
  'Rue Souani',
  'Avenue Mohammed VI',
  'Boulevard Rachidi',
  'Rue Prince Moulay Abdellah',
  'Place des Nations Unies',
  'Avenue Pasteur',
  'Derb Sultan',
  'Boulevard de Bordeaux',
  'Avenue Al Qods',
  'Boulevard Yaacoub Al Mansour',
  'Rue de Paris',
  'Avenue Lalla Yacout',
  'Rue Sebta (Ceuta)',
  'Boulevard d’Oued Zem',
  'Rue Karatchi',
  'Avenue Moulay Rachid',
  'Boulevard Ghandi',
  'Rue Oum Errabia',
  'Avenue des Forces Auxiliaires',
  'Rue Cadi Ayad',
  'Boulevard Rahal El Meskini',
  'Avenue du 2 Mars',
  'Rue Nador',
  'Boulevard Zerouali',
  'Rue Tantan',
  'Avenue Houmane El Fetouaki',
  'Boulevard Abdelkarim Al Khattabi',
  'Rue Idriss Al Akber',
  'Avenue Fal Ould Oumeir',
  'Boulevard de la Corniche',
  'Rue Jemaa el-Fna',
  'Avenue des Orangers',
  'Rue Bab Agnaou',
  'Boulevard Ibn Sina (Avicenne)',
  'Rue Kénitra',
  'Avenue Imam Malik',
  'Boulevard Mohammed Zefzaf',
  'Rue Tariq Bnou Ziad',
  'Avenue Abdelkrim Sahraoui'
];

export const cities = [
  "Casablanca",
  "Rabat",
  "Marrakech",
  "Fès",
  "Tanger",
  "Agadir",
  "Meknès",
  "Oujda",
  "Salé",
  "Kénitra",
  "Tétouan",
  "Safi",
  "Mohammédia",
  "Essaouira",
  "Beni Mellal",
  "Nador",
  "Al Hoceïma",
  "Ouarzazate",
  "Chefchaouen",
  "Laâyoune"
];

export const conditions = [
  'Asthma',
  'Allergies (peanuts)',
  'Diabetes Type 1',
  'Lactose intolerance',
  'Gluten sensitivity',
  'Seasonal allergies',
  'Requires glasses for reading',
  'None reported',
  'Severe bee sting allergy (Requires EpiPen)',
  'Eczema (requires topical cream)',
  'Epilepsy (seizure disorder)',
  'ADHD/ADD',
  'Dyslexia (requires modified testing)',
  'Celiac disease',
  'Food allergies (shellfish)',
  'Hearing impairment (requires hearing aids)',
  'Vision impairment (legally blind in one eye)',
  'Hemophilia',
  'Migraines (severe, requiring rest)',
  'Heart murmur (monitored by doctor)',
  'Anaphylaxis history (specify allergen)',
  'Requires a specific seating arrangement',
  'Mobility issues (uses crutches/wheelchair)',
  'Requires frequent supervised breaks',
];

export const schoolNames = [
  'Groupe Résidence',
  'Khalil Gibran School',
  'Dar Essalam School',
  'École Massignon',
  'Institut Palmiers',
  'École Maupassant',
  'École Andalous',
  'École Claude Monet',
  'École Victor Hugo',
  'Groupe Lyautey',
  'Institut Français',
  'École Alphonse Daudet',
  'Groupe Paul Valéry',

  'Al Jabr School',
  'Al Akhawayn School',
  'Al Maarifa Academy',
  'Groupe Scolaire Anfa',
  'Institut Al Madina',
  'Groupe Atlas',
  'Groupe Scolaire La Résidence',
  'Ecole Les Oiseaux',
  'Groupe Moulay Youssef',

  'École Al Qods',
  'Madrassat Al Irfan',
  'Institut Islamique ikraa',
  'École Mohammed V',
  'Groupe Moulay Idriss',
  'Madrassat Al Fath',
  'Institut Assouna',
  'École Imam Malik',

  'Groupe Scolaire Al Mansour',
  'École Moulay Rachid',
  'École Moulay Ismail',
  'Institut Omar Al Khayam',
  'Groupe Al Khawarizmi',
  'Groupe Scolaire Les Nirvanes',
  'Ecole La Colombe',
  'École Les Oliviers',
  'Institut Al Ghazali'
];

export const relationshipType = ['father', 'mother', 'guardian', 'stepparent', 'grandparent', 'other'];
export const maritalStatus = ['single', 'married', 'divorced', 'widowed', 'separated']
export const schedules = ['monthly', 'quarterly', 'semester', 'annually', 'oneTime'];

export const classesData = [
  { id: "CLS00", name: "PS", description: "Petite Section", level: "Maternelle" },
  { id: "CLS01", name: "MS", description: "Moyenne Section", level: "Maternelle" },
  { id: "CLS02", name: "GS", description: "Grande Section", level: "Maternelle" },
  { id: "CLS03", name: "CP", description: "Cours Préparatoire", level: "Primaire" },
  { id: "CLS04", name: "CE1", description: "Cours Élémentaire 1ère année", level: "Primaire" },
  { id: "CLS05", name: "CE2", description: "Cours Élémentaire 2ème année", level: "Primaire" },
  { id: "CLS06", name: "CM1", description: "Cours Moyen 1ère année", level: "Primaire" },
  { id: "CLS07", name: "CM2", description: "Cours Moyen 2ème année", level: "Primaire" },
  { id: "CLS08", name: "CE6", description: "Sixième - Début du collège", level: "Collège" },
  { id: "CLS09", name: "1AC", description: "1ère année collège", level: "Collège" },
  { id: "CLS10", name: "2AC", description: "2ème année collège", level: "Collège" },
  { id: "CLS11", name: "3AC", description: "3ème année collège", level: "Collège" },
  { id: "CLS12", name: "TC", description: "Tronc Commun", level: "Lycée" },
  { id: "CLS13", name: "1BAC", description: "1ère année Baccalauréat", level: "Lycée" },
  { id: "CLS14", name: "2BAC", description: "2ème année Baccalauréat", level: "Lycée" }
];

export const subjectsData = [
  {
    "id": "SB00",
    "code": "MATH",
    "name": "Mathématiques",
    "description": "Cours de mathématiques incluant l'arithmétique, la géométrie et l'algèbre"
  },
  {
    "id": "SB01",
    "code": "FR",
    "name": "Français",
    "description": "Langue française, littérature, grammaire et expression écrite"
  },
  {
    "id": "SB02",
    "code": "AR",
    "name": "العربية",
    "description": "اللغة العربية والأدب العربي والقواعد النحوية"
  },
  {
    "id": "SB03",
    "code": "PHY",
    "name": "Physique",
    "description": "Physique et chimie, mécanique, électricité et thermodynamique"
  },
  {
    "id": "SB04",
    "code": "SVT",
    "name": "Sciences de la Vie et de la Terre",
    "description": "Biologie, géologie, écologie et sciences naturelles"
  },
  {
    "id": "SB05",
    "code": "HIST",
    "name": "Histoire",
    "description": "Histoire du monde et du Maroc"
  },
  {
    "id": "SB06",
    "code": "GEO",
    "name": "Géographie",
    "description": "Géographie physique et humaine"
  },
  {
    "id": "SB07",
    "code": "ENG",
    "name": "English",
    "description": "English language and literature"
  },
  {
    "id": "SB08",
    "code": "PE",
    "name": "Éducation Physique",
    "description": "Sport et éducation physique"
  },
  {
    "id": "SB09",
    "code": "ART",
    "name": "Arts Plastiques",
    "description": "Dessin, peinture et arts créatifs"
  },
  {
    "id": "SB10",
    "code": "MUS",
    "name": "Musique",
    "description": "Théorie musicale et pratique instrumentale"
  },
  {
    "id": "SB11",
    "code": "INFO",
    "name": "Informatique",
    "description": "Initiation à l'informatique et programmation"
  },
  {
    "id": "SB12",
    "code": "ECR",
    "name": "Éducation Civique",
    "description": "Éducation civique et morale"
  }
]

export const feeTypeData =[
  {
    "id": "FT00",
    "name": "Tuition Fee",
    "description": "Monthly tuition fee for academic year",
    "category": "tuition",
    "amount": 1100,
    "paymentType": "recurring",
    "status": "active"
  },
  {
    "id": "FT01",
    "name": "Registration Fee",
    "description": "One-time registration fee for new students",
    "category": "registration",
    "amount": 1000,
    "paymentType": "oneTime",
    "status": "active"
  },
  {
    "id": "FT02",
    "name": "Transport Fee",
    "description": "Monthly school bus transportation fee",
    "category": "transport",
    "amount": 100,
    "paymentType": "recurring",
    "status": "active"
  },
  {
    "id": "FT03",
    "name": "Cafeteria Fee",
    "description": "Monthly school cafeteria and meal service fee",
    "category": "cafeteria",
    "amount": 400,
    "paymentType": "recurring",
    "status": "active"
  },
  {
    "id": "FT04",
    "name": "Books & Materials",
    "description": "Textbooks and study materials fee",
    "category": "books",
    "amount": 300,
    "paymentType": "oneTime",
    "status": "active"
  },
  {
    "id": "FT05",
    "name": "Sports Fee",
    "description": "Annual sports and athletic programs fee",
    "category": "sports",
    "amount": 250,
    "paymentType": "oneTime",
    "status": "active"
  },
  {
    "id": "FT06",
    "name": "Uniform Fee",
    "description": "School uniform and dress code items",
    "category": "uniform",
    "amount": 350,
    "paymentType": "oneTime",
    "status": "active"
  },
  {
    "id": "FT07",
    "name": "Technology Fee",
    "description": "Computer lab and digital learning resources",
    "category": "technology",
    "amount": 200,
    "paymentType": "recurring",
    "status": "active"
  },
  {
    "id": "FT8",
    "name": "Field Trip Fee",
    "description": "Educational excursions and field trips",
    "category": "fieldtrip",
    "amount": 200,
    "paymentType": "oneTime",
    "status": "active"
  }
]

export const vehiclesData = [
  {
    "id": "VH00",
    "name": "Atlas Express 1",
    "brand": "Mercedes-Benz",
    "model": "Tourismo",
    "year": 2020,
    "type": "fullbus",
    "capacity": 55,
    "licensePlate": "A-12345-20",
    "driverId": "DRV01",
    "image": "mercedes-tourismo-1.jpg",
    "purchaseDate": "2020-01-15",
    "purchasePrice": "850000.00",
    "initialMileage": "0.00",
    "currentMileage": "185420.50",
    "status": "active",
    "notes": "Main long-distance bus. Excellent condition with regular maintenance."
  },
  {
    "id": "VH01",
    "name": "City Shuttle 2",
    "brand": "Iveco",
    "model": "Daily Minibus",
    "year": 2021,
    "type": "minibus",
    "capacity": 22,
    "licensePlate": "B-67890-21",
    "driverId": "DRV02",
    "image": "iveco-daily-2.jpg",
    "purchaseDate": "2021-03-20",
    "purchasePrice": "320000.00",
    "initialMileage": "0.00",
    "currentMileage": "98765.30",
    "status": "active",
    "notes": "Perfect for city routes and shorter trips. Very fuel efficient."
  },
  {
    "id": "VH02",
    "name": "Desert Runner 3",
    "brand": "Volvo",
    "model": "9700 HD",
    "year": 2019,
    "type": "fullbus",
    "capacity": 49,
    "licensePlate": "C-11223-19",
    "driverId": "DRV03",
    "image": "volvo-9700-3.jpg",
    "purchaseDate": "2019-06-10",
    "purchasePrice": "780000.00",
    "initialMileage": "0.00",
    "currentMileage": "245680.75",
    "status": "active",
    "notes": "Reliable workhorse for medium to long routes. Recent engine overhaul."
  },
  {
    "id": "VH03",
    "name": "Coastal Express 4",
    "brand": "Scania",
    "model": "Touring HD",
    "year": 2022,
    "type": "fullbus",
    "capacity": 53,
    "licensePlate": "D-44556-22",
    "driverId": "DRV05",
    "image": "scania-touring-4.jpg",
    "purchaseDate": "2022-04-05",
    "purchasePrice": "920000.00",
    "initialMileage": "0.00",
    "currentMileage": "67234.20",
    "status": "active",
    "notes": "Newest addition to fleet. Premium features and excellent comfort."
  },
  {
    "id": "VH04",
    "name": "Mountain Climber 5",
    "brand": "MAN",
    "model": "Lion's Coach",
    "year": 2018,
    "type": "fullbus",
    "capacity": 51,
    "licensePlate": "E-78901-18",
    "driverId": null,
    "image": "man-lions-5.jpg",
    "purchaseDate": "2018-09-15",
    "purchasePrice": "720000.00",
    "initialMileage": "0.00",
    "currentMileage": "312450.90",
    "status": "maintenance",
    "notes": "Currently in maintenance. Annual inspection and brake system overhaul."
  },
  {
    "id": "VH05",
    "name": "Urban Link 6",
    "brand": "Toyota",
    "model": "Coaster",
    "year": 2023,
    "type": "minibus",
    "capacity": 29,
    "licensePlate": "F-23456-23",
    "driverId": null,
    "image": "toyota-coaster-6.jpg",
    "purchaseDate": "2023-02-10",
    "purchasePrice": "380000.00",
    "initialMileage": "0.00",
    "currentMileage": "34567.80",
    "status": "active",
    "notes": "Ideal for corporate shuttles and small group tours. Low mileage."
  },
  {
    "id": "VH06",
    "name": "Heritage Route 7",
    "brand": "Setra",
    "model": "S 516 HD",
    "year": 2017,
    "type": "fullbus",
    "capacity": 48,
    "licensePlate": "G-99888-17",
    "driverId": null,
    "image": "setra-516-7.jpg",
    "purchaseDate": "2017-11-20",
    "purchasePrice": "690000.00",
    "initialMileage": "0.00",
    "currentMileage": "398750.45",
    "status": "inactive",
    "notes": "Scheduled for retirement. Being evaluated for sale or conversion to backup vehicle."
  },
  {
    "id": "VH07",
    "name": "Speedway Pro 8",
    "brand": "Neoplan",
    "model": "Jetliner",
    "year": 2021,
    "type": "fullbus",
    "capacity": 54,
    "licensePlate": "H-55667-21",
    "driverId": "DRV04",
    "image": "neoplan-jetliner-8.jpg",
    "purchaseDate": "2021-07-12",
    "purchasePrice": "890000.00",
    "initialMileage": "0.00",
    "currentMileage": "142350.65",
    "status": "active",
    "notes": "High-speed intercity bus with premium amenities and reclining seats."
  },
  {
    "id": "VH08",
    "name": "Express Link 9",
    "brand": "King Long",
    "model": "XMQ6127",
    "year": 2020,
    "type": "minibus",
    "capacity": 35,
    "licensePlate": "I-34521-20",
    "driverId": null,
    "image": "kinglong-xmq-9.jpg",
    "purchaseDate": "2020-05-08",
    "purchasePrice": "450000.00",
    "initialMileage": "0.00",
    "currentMileage": "156789.40",
    "status": "active",
    "notes": "Reliable minibus for mid-range routes. Regular maintenance schedule maintained."
  },
  {
    "id": "VH09",
    "name": "Premium Traveler 10",
    "brand": "Yutong",
    "model": "ZK6147H",
    "year": 2022,
    "type": "fullbus",
    "capacity": 56,
    "licensePlate": "J-12378-22",
    "driverId": "DRV06",
    "image": "yutong-zk6147-10.jpg",
    "purchaseDate": "2022-08-20",
    "purchasePrice": "795000.00",
    "initialMileage": "0.00",
    "currentMileage": "89234.55",
    "status": "active",
    "notes": "Latest model with advanced safety features and eco-friendly engine."
  }
]